#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width    1
bspc config border_radius   5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config window_gap           10

bspc config focused_border_color  '#efefef'
bspc config active_border_color   '#303030'
bspc config normal_border_color   '#303030'

bspc rule -a Gimp desktop='^8' state=floating follow=on
