#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scratchpad sticky=on state=floating hidden=on
st -c scratchpad -e ~/.config/bspwm/scratch &

bspc rule -a Gimp desktop='^8' state=floating follow=on
