#!/bin/bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	3
bspc config window_gap          	10
bspc config border_radius		0
#bspc config focused_border_color	'#FF8C00'
bspc config focused_border_color	'#FF00FF'
bspc config normal_border_color		'#FF00FF'
bspc config urgent_border_color		'#FF00FF'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a <window class>:<window instance> state=floating

# pop-up calc/terminal
bspc rule -a scratchpad sticky=on state=floating
