#!/bin/bash
IFS=$'\t' mpd_array=( $(MPD_HOST=127.0.0.1 MPD_PORT=6600 \
          mpc --format "\t%artist%\t%album%\t%file%\t") );

filename="conky_cover.png";
placeholder="$HOME/.config/conky/placeholder.png"

if [[ ! -f /tmp/"${mpd_array[1]}".album ]] ; then
  rm -f /tmp/*.album &> /dev/null;
  >/tmp/"${mpd_array[1]}".album;

  album=`dirname "/home/feint/Music/${mpd_array[2]}"`;
  cover=$album"/"`ls $album | egrep "jpeg|jpg|png|gif" | head -n 1`;


  # if either mpd is offline, or no album art is found
  if ( [ ! -f $cover ] || [ ! pgrep -x mpd ] ); then
    convert $placeholder -quality 95 -density 400 -sharpen 0x1.2 \
                    -resize x180 -gravity center -crop 180x180+0+0 +repage \
                    /tmp/$filename
  else
    # this is the bigger image for conky
    convert $cover -quality 95 -density 400 -sharpen 0x1.2 \
                    -resize x180 -gravity center -crop 180x180+0+0 \
                    +repage /tmp/$filename

    # our dunst notification w/ an icon
    img_uuid=$(uuidgen)
    rm -rf /tmp/mpd_dunst_icon_uuid
    echo $img_uuid > /tmp/mpd_dunst_icon_uuid 

    icon_path="/tmp/MPD_$img_uuid.png"

    # delete the super old thumbnails
    garbage_collect=$(find /tmp/ -not -newermt '-5 seconds' -type f -delete -name "MPD*.png")
    for i in garbage_collect; do
        rm -rf "$i"
    done

    convert $cover -quality 95 -density 400 -sharpen 0x1.2 \
                    -resize x75 -gravity center -crop 75x75+0+0 +repage \
                    $icon_path

    IFS=$'\t' read album artist title \
            <<< "$(mpc --format="%album%\t%artist%\t%title%")"
    notify-send -u low --app-name=mpd --icon=$icon_path \
            "Now playing" "$title by $artist"
  fi
fi
