#!/usr/bin/env bash

tty=`tty`
tty_has_polybar=[ `ps x | grep polybar | grep ${tty:5} ]

# check if process is _not_ running on this tty
if [ -z pgrep -x "polybar" > /dev/null ] || [ -z tty_has_polybar ] 
then
	polybar --config $HOME/.config/polybar/config
fi
